version: ' 3'
services:
  web:
    container_name: VEX_EC
    #image: php:8.3-apache
    build: ./docker/web/dockerfile
    environment:
      TZ: "Asia/Tokyo"
    ports:
      - "80:80"
    volumes:
      - ./app/htdocs:/var/www/html