version: '3.8'
services:
  web:
    container_name: VEX_EC
    build:
      context: ./docker/web
      dockerfile: dockerfile
    environment:
      TZ: "Asia/Tokyo"
    ports:
      - "80:80"
    volumes:
      - ./app/htdocs:/var/www/html
    working_dir: /var/www/html